### ISSUE TITLE
Query parameters prefixed with '$' are getting stripped off

### ISSUE THREAD

**Issue by tarvainen** [troyanskiy/ng2-resource-rest#104]
Hello!

My backend wants me to pass my query parameters prefixed with '$', for example `{  $skip: 25 }`. However when I create a request like this

```
@ResourceAction({
  path: '/'
})
list: ResourceMethod<{ $skip: number }, string[]>;

.....

const list = myResource.list({ $skip: 2 });
```

the request is made without any query parameters at all. When I strip down those '$' characters, the request works like a charm and parameters are passed properly.  I tracked down the problem all way down to this line:

https://github.com/troyanskiy/ng2-resource-rest/blob/master/src/ResourceAction.ts#L462

where these '$'-prefixed values are just getting ignored. I can get around this by rolling back to version 2.0.1 but that's not really a real solution.

Now I am just wondering whether this is a functionality or a bug since it really seems like a functionality but feels like a bug to me.

**Comment by troyanskiy** [comment]
Yes... Now all $prefixes are removed from request object because we have `system` $ prefixes.
I will do something for that now.

**Comment by troyanskiy** [comment]
Hi again.
I have published new version.
On resource object you have now predefined cleanData method which does cleaning now only "system" properties from the object.
It will remove by default functions and `$resolved`, `$observable`, `$abortRequest` and `$resource` properties.
Additionally you can skip that cleaning completely by adding flag `skipDataCleaning: true` to your `ResourceAction` decorator but I **do not recommend** to added it because it will send 'unwanted' data to the backend.
So in your case if you don't have send properties like `$resolved`, `$observable`, `$abortRequest` and `$resource` it will work without any changes, just update the lib.

Thank you for the issue.

**Comment by tarvainen** [comment]
Hi, that was a fast one!

It seems to be working now beautifully. Thanks!

Closing this as resolved.
