### ISSUE TITLE
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by 90lucasgabriel** [troyanskiy/ng2-resource-rest#69]
Return this error with ng2-resource-rest, but http.get() works.
![image](https://cloud.githubusercontent.com/assets/9625765/21482998/b5703afc-cb62-11e6-8643-5cac872eb9d1.png)

**Comment by troyanskiy** [comment]
Could you please provide your resource file and app module sources?

**Comment by 90lucasgabriel** [comment]
My repo: https://github.com/90lucasgabriel/shop 

- /src/pages/product/product-list/product-list.ts -> 
- /src/pages/product/product.service.ts -> 
- /src/pages/product/product.resource.ts


Thank you.

**Comment by troyanskiy** [comment]
The problem is related to AOT compilation.
Please check code comments below

1. Resource file
```typescript
@Injectable()
@ResourceParams({
  url: 'https://randomuser.me/api/?results=10',

  // Add that add2Providers: false parameter to not add to providers array
  add2Provides: false
})
export class ProductResource extends Resource {

  constructor(http: Http, injector: Injector){
    super(http, injector);
  }

  @ResourceAction({
    isArray: true,

    // I have added that responseInterceptor here because you receive from randomuser.me not
    // not really an array, it's an object with array
    // if you want to receive an object, than remove isArray param.
    responseInterceptor: (observable: Observable<Response>): Observable<any> => {
      return observable.map(res => res.json().results);
    }
  })
  query: ResourceMethod<IQueryInput, any[]>;
}
```

2. Product Module
``` typescript
@NgModule({
  imports:      [
    IonicModule.forRoot(ProductListPage),
    IonicModule.forRoot(ProductDetailsPage)
  ],
  declarations: [
    ProductListPage,
    ProductDetailsPage
  ],
  exports: [
    ProductListPage,
    ProductDetailsPage
  ]
})
export class ProductModule {
  // Since the resource belongs to the submodule, then I would add the resource here
  // and call forRoot in your main module
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: ProductModule,
      providers: [
        ProductResource
      ]
    };
  }
}
```

3. Main module

``` typescript
@NgModule({
  declarations: [
    MyApp
  ],
  imports: [
    IonicModule.forRoot(MyApp),
    ResourceModule.forRoot(),
    // Here is for root
    ProductModule.forRoot()
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ],
  providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}]
})
export class AppModule {}
```

I have created a pool request to your project with the changes if you need them.

**Comment by 90lucasgabriel** [comment]
Wowwwww!!! It worked!!
Thanks for the solution and the comments.

**Comment by troyanskiy** [comment]
You are welcome.

**Comment by marshall007** [comment]
@troyanskiy so the only way to avoid this issue is by explicitly specifying the `constructor` when extending `Resource`? I assume this is because TypeScript does not generate a default constructor on the child class with the same arguments, thus breaking Angular DI?

Is there a recommended workaround for avoiding this boilerplate in every `Resource` we create?

I would be concerned that if/when arguments to the base `Resource` class change, we'd have to update it everywhere. Perhaps we should at least update `Resource` to just have a single `Injector` argument?

**Comment by marshall007** [comment]
@troyanskiy just to follow up, per https://github.com/angular/angular/commit/f5c8e0989d85bc064f689fc3595207dfb29413f4 it seems like this should be working without specifying a `constructor` in the child class. Do you know if there are any caveats to that? Is it because `Resource` is not marked as `@Injectable()`?
